title: Sencilla
author:
  name: Jane Doe
  email: janedoe@example.com
description: >-  #this means to ignore newlines until "show_excerpts:"
  A minimal Jekyll theme with LaTeX support.

url: ""

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins: 
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate


